/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CredentialRegistry__factory } from "./CredentialRegistry__factory";
export { InstitutionRegistry__factory } from "./InstitutionRegistry__factory";
