/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CredentialRegistry } from "./CredentialRegistry";
export type { InstitutionRegistry } from "./InstitutionRegistry";
export * as factories from "./factories";
export { CredentialRegistry__factory } from "./factories/CredentialRegistry__factory";
export { InstitutionRegistry__factory } from "./factories/InstitutionRegistry__factory";
